"""Build the feature matrix for the traffic-volume forecasting task.

Reads from the Gold layer (`gold.fact_traffic_monthly` joined to its
dimensions) and produces a tidy, model-ready DataFrame.

Output schema:

| Column        | Type   | Notes                                          |
|---------------|--------|------------------------------------------------|
| month_start   | date   | Used by `time_split`; not a feature            |
| volume_total  | int    | Target                                         |
| plaza_name    | str    | Kept for serving lookup; not a feature         |
| vehicle_type  | str    | Kept for serving lookup; not a feature         |
| direction     | str    | Kept for serving lookup; not a feature         |
| plaza_id      | int    | Categorical code of plaza_name                 |
| vehicle_id    | int    | Categorical code of vehicle_type               |
| direction_id  | int    | Categorical code of direction                  |
| year          | int    | From month_start                               |
| month         | int    | 1..12, from month_start                        |
| lag_1         | float  | volume_total one month ago, same key           |
| lag_12        | float  | volume_total twelve months ago, same key       |

Rows missing `lag_1` or `lag_12` (the first 12 months of any plaza/
direction/vehicle series) are dropped.

Trainees do not edit this file. Feature engineering is pre-baked so the
day's hands-on work stays on the MLflow lifecycle.
"""
from __future__ import annotations

import os

import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import Engine


FEATURE_COLS = [
    "plaza_id", "vehicle_id", "direction_id",
    "year", "month", "lag_1", "lag_12",
]
TARGET_COL = "volume_total"
KEY_COLS = ["plaza_name", "vehicle_type", "direction"]


def build_engine() -> Engine:
    """Build a SQLAlchemy engine from POSTGRES_* env vars."""
    host = os.environ["POSTGRES_HOST"]
    port = os.environ.get("POSTGRES_PORT", "5432")
    db = os.environ["POSTGRES_DB"]
    user = os.environ["POSTGRES_USER"]
    password = os.environ["POSTGRES_PASSWORD"]
    return create_engine(
        f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}"
    )


def _load_gold(engine: Engine) -> pd.DataFrame:
    query = """
        select
            d.month_start,
            p.plaza_name,
            v.vehicle_type,
            f.direction,
            f.volume_total
        from gold.fact_traffic_monthly as f
        join gold.dim_date    as d on d.date_key    = f.date_key
        join gold.dim_plaza   as p on p.plaza_key   = f.plaza_key
        join gold.dim_vehicle as v on v.vehicle_key = f.vehicle_key
    """
    return pd.read_sql(query, engine, parse_dates=["month_start"])


def _encode(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["plaza_id"]     = df["plaza_name"].astype("category").cat.codes.astype("int32")
    df["vehicle_id"]   = df["vehicle_type"].astype("category").cat.codes.astype("int32")
    df["direction_id"] = df["direction"].astype("category").cat.codes.astype("int32")
    df["year"]  = df["month_start"].dt.year.astype("int32")
    df["month"] = df["month_start"].dt.month.astype("int32")
    return df


def _add_lags(df: pd.DataFrame) -> pd.DataFrame:
    df = df.sort_values(
        ["plaza_id", "direction_id", "vehicle_id", "month_start"]
    ).reset_index(drop=True)
    key = ["plaza_id", "direction_id", "vehicle_id"]
    df["lag_1"]  = df.groupby(key)[TARGET_COL].shift(1)
    df["lag_12"] = df.groupby(key)[TARGET_COL].shift(12)
    return df.dropna(subset=["lag_1", "lag_12"]).reset_index(drop=True)


def build_features(engine: Engine | None = None) -> pd.DataFrame:
    """Return the model-ready feature matrix from the Gold layer.

    Pass an explicit `engine` for testing or programmatic use; otherwise
    one is built from POSTGRES_* environment variables.
    """
    if engine is None:
        engine = build_engine()
    raw = _load_gold(engine)
    encoded = _encode(raw)
    final = _add_lags(encoded)
    return final
