"""Time-aware train/test split for the traffic-volume forecasting task.

The traffic data is a time series: each row has a `month_start` column.
A naive random split would leak future observations into the training
set and produce wildly optimistic metrics. `time_split` reserves the
last `holdout_months` of data as the test set; everything before is
training.

Trainees do not edit this file. The split is pre-baked so the day's
hands-on work stays on the MLflow lifecycle.
"""
from __future__ import annotations

import pandas as pd


def time_split(
    df: pd.DataFrame,
    holdout_months: int = 6,
    date_col: str = "month_start",
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Split `df` into train/test, reserving the last `holdout_months`.

    `df` must have `date_col` parseable as a date. The cutoff is
    `max(date) - holdout_months`; rows strictly after the cutoff land
    in the test set. The input DataFrame is not mutated.
    """
    if holdout_months < 1:
        raise ValueError("holdout_months must be >= 1")
    if date_col not in df.columns:
        raise KeyError(f"date column {date_col!r} not in df")

    dates = pd.to_datetime(df[date_col])
    cutoff = dates.max() - pd.DateOffset(months=holdout_months)

    train = df.loc[dates <= cutoff].copy()
    test = df.loc[dates > cutoff].copy()
    return train, test
